name: dlsite illust rss

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"

      - name: Install gems
        run: bundle install

      - name: Run scraper
        run: ruby scraper.rb

      - name: Commit DB
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add dlsite.db
          git commit -m "Update database" || echo "No changes"
          git push

            - name: Export weekly CSV
        run: |
          sqlite3 dlsite.db "headers on" ".mode csv" ".output v_share_all.csv" "SELECT * FROM works;"
          
      - name: Commit CSV
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"
          git add v_share_all.csv
          git commit -m "Update weekly CSV" || echo "No changes"
          git push
